### Create a new post
POST  http://localhost:3000/api/feed
Content-Type: application/json

{
  "body": "Be a body 11"
}

### Create a new post
POST  http://localhost:3000/api/feed
Content-Type: application/json

{
  "body": "Don't be a body"
}

### Pagination testing
GET http://localhost:3000/api/feed?take=20&skip=2

### Update post
PUT http://localhost:3000/api/feed/1
Content-Type: application/json

{
  "body": "Updated body"
}

### Delete post
DELETE http://localhost:3000/api/feed/1
Content-Type: application/json