### Create a new post (get a new token)
POST  http://localhost:3000/api/feed
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoyLCJmaXJzdE5hbWUiOiJVbmNsZSIsImxhc3ROYW1lIjoiQm9iIiwiZW1haWwiOiJ1bmNsZWJvYkBlbWFpbC5jb20iLCJyb2xlIjoidXNlciJ9LCJpYXQiOjE2NzkwMDQ3NjYsImV4cCI6MTY3OTAwODM2Nn0.8Vzr8AMGdWsVPNCdyilUiNi2FRR66p-ykg87dXdprv8
Content-Type: application/json

{
  "body": "Be a body 25"
}

### Create a new post
POST  http://localhost:3000/api/feed
Content-Type: application/json

{
  "body": "Don't be a body"
}

### Pagination testing (take 20, skip 0)
GET http://localhost:3000/api/feed?take=20&skip=0

### Update post
PUT http://localhost:3000/api/feed/1
Content-Type: application/json

{
  "body": "Updated body"
}

### Delete post
DELETE http://localhost:3000/api/feed/1
Content-Type: application/json